using System;
using System.IO;
using HuyenLo.Runtime;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace HuyenLo.Editor
{
    public static class SliceBuild
    {
        [MenuItem("Huyền Lộ/Create VS-1 scene")]
        public static void CreateScene() {
            AssetDatabase.ImportAsset("Assets/HuyenLo/Resources/Fonts/DejaVuSans.ttf");
            var fontImporter=(TrueTypeFontImporter)AssetImporter.GetAtPath("Assets/HuyenLo/Resources/Fonts/DejaVuSans.ttf");
            fontImporter.includeFontData=true;fontImporter.SaveAndReimport();
            var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);
            new GameObject("LocalAuthority VS1").AddComponent<SliceHost>();
            Directory.CreateDirectory("Assets/HuyenLo/Scenes");EditorSceneManager.SaveScene(scene,"Assets/HuyenLo/Scenes/VS1.unity");
            EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene("Assets/HuyenLo/Scenes/VS1.unity",true)};
            PlayerSettings.companyName="HuyenLo";PlayerSettings.productName="Huyen Lo VS1";
            PlayerSettings.defaultScreenWidth=1280;PlayerSettings.defaultScreenHeight=720;PlayerSettings.runInBackground=true;
            AssetDatabase.SaveAssets();Debug.Log("[VS1] Scene generated by Editor API.");
        }
        [MenuItem("Huyền Lộ/Build Linux VS-1")]
        public static void Linux() {
            CreateScene();Directory.CreateDirectory("Builds/Linux");
            var report=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{"Assets/HuyenLo/Scenes/VS1.unity"},locationPathName="Builds/Linux/HuyenLo.x86_64",target=BuildTarget.StandaloneLinux64,options=BuildOptions.Development});
            Debug.Log($"[VS1] Build {report.summary.result}; {report.summary.totalSize} bytes");
            if(report.summary.result!=BuildResult.Succeeded)throw new Exception("VS-1 build failed");
        }
    }
}
