using System;
using System.IO;
using HuyenLo.Runtime;
using UnityEditor;
using UnityEditor.Build.Reporting;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace HuyenLo.Editor
{
    public static class SliceBuild
    {
        [MenuItem("Huyền Lộ Prototype/Create VS-1 scene")]
        public static void CreateScene() {
            AssetDatabase.ImportAsset("Assets/_Prototype/VS1_EndToEnd/Resources/Fonts/DejaVuSans.ttf");
            var fontImporter=(TrueTypeFontImporter)AssetImporter.GetAtPath("Assets/_Prototype/VS1_EndToEnd/Resources/Fonts/DejaVuSans.ttf");
            fontImporter.includeFontData=true;fontImporter.SaveAndReimport();
            var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);
            new GameObject("LocalAuthority VS1").AddComponent<SliceHost>();
            Directory.CreateDirectory("Assets/_Prototype/VS1_EndToEnd/Scenes");EditorSceneManager.SaveScene(scene,"Assets/_Prototype/VS1_EndToEnd/Scenes/VS1.unity");
            EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene("Assets/_Prototype/VS1_EndToEnd/Scenes/VS1.unity",true)};
            PlayerSettings.companyName="HuyenLo";PlayerSettings.productName="Huyen Lo Prototype V6.2.7";
            PlayerSettings.defaultScreenWidth=1280;PlayerSettings.defaultScreenHeight=720;PlayerSettings.runInBackground=true;
            AssetDatabase.SaveAssets();Debug.Log("[VS1] Scene generated by Editor API.");
        }
        [MenuItem("Huyền Lộ Prototype/Build Linux VS-1")]
        public static void Linux() {
            CreateScene();Directory.CreateDirectory("Builds/Prototype/VS1_EndToEnd");
            var report=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{"Assets/_Prototype/VS1_EndToEnd/Scenes/VS1.unity"},locationPathName="Builds/Prototype/VS1_EndToEnd/HuyenLo.x86_64",target=BuildTarget.StandaloneLinux64,options=BuildOptions.Development});
            Debug.Log($"[VS1] Build {report.summary.result}; {report.summary.totalSize} bytes");
            if(report.summary.result!=BuildResult.Succeeded)throw new Exception("VS-1 build failed");
        }
    }
}
